<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 20px;
        }
        h1 {
            text-align: center;
            font-size: 24px;
            color: #333;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            color: #333;
        }
        .severity-LOW {
            background-color: #5fbb31;
            color: white;
        }
        .severity-MEDIUM {
            background-color: #e9c600;
            color: white;
        }
        .severity-HIGH {
            background-color: #ff8800;
            color: white;
        }
        .severity-CRITICAL {
            background-color: #e40000;
            color: white;
        }
        .severity-UNKNOWN {
            background-color: #747474;
            color: white;
        }
        .links a {
            color: #1a73e8;
            text-decoration: none;
        }
        .links a:hover {
            text-decoration: underline;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #666;
            margin-top: 20px;
        }
    </style>
    <title>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }}</title>
</head>
<body>
    <h1>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }}</h1>
    <table>
    {{- range . }}
        <tr class="group-header"><th colspan="6">{{ .Type | toString | escapeXML }}</th></tr>
        {{- if (eq (len .Vulnerabilities) 0) }}
        <tr><td colspan="6" style="text-align: center;">No Vulnerabilities found</td></tr>
        {{- else }}
        <tr class="sub-header">
            <th>Package</th>
            <th>Vulnerability ID</th>
            <th>Severity</th>
            <th>Installed Version</th>
            <th>Fixed Version</th>
            <th>Links</th>
        </tr>
        {{- range .Vulnerabilities }}
        <tr class="severity-{{ escapeXML .Vulnerability.Severity }}">
            <td>{{ escapeXML .PkgName }}</td>
            <td>{{ escapeXML .VulnerabilityID }}</td>
            <td class="severity">{{ escapeXML .Vulnerability.Severity }}</td>
            <td>{{ escapeXML .InstalledVersion }}</td>
            <td>{{ escapeXML .FixedVersion }}</td>
            <td class="links">
                {{- range .Vulnerability.References }}
                <a href={{ escapeXML . | printf "%q" }}>{{ escapeXML . }}</a><br>
                {{- end }}
            </td>
        </tr>
        {{- end }}
        {{- end }}
        {{- if (eq (len .Misconfigurations ) 0) }}
        <tr><td colspan="6" style="text-align: center;">No Misconfigurations found</td></tr>
        {{- else }}
        <tr class="sub-header">
            <th>Type</th>
            <th>Misconf ID</th>
            <th>Check</th>
            <th>Severity</th>
            <th>Message</th>
        </tr>
        {{- range .Misconfigurations }}
        <tr class="severity-{{ escapeXML .Severity }}">
            <td>{{ escapeXML .Type }}</td>
            <td>{{ escapeXML .ID }}</td>
            <td>{{ escapeXML .Title }}</td>
            <td class="severity">{{ escapeXML .Severity }}</td>
            <td>{{ escapeXML .Message }}</td>
            <td class="links">
                <a href={{ escapeXML .PrimaryURL | printf "%q" }}>{{ escapeXML .PrimaryURL }}</a>
            </td>
        </tr>
        {{- end }}
        {{- end }}
    {{- end }}
    </table>
    <div class="footer">
        <p>Generated by Trivy - Vulnerability and Misconfiguration Scanner</p>
    </div>
</body>
</html>
